mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from polls import views as polls_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include(('polls.urls', 'polls'), namespace= 'polls')),
    path('api/', polls_views.exampleList.as_view(), name='api'),
    path('login/', auth_views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='polls/logout.html'), name='logout'),
    path('register/', polls_views.register, name = 'register'),
    path('', polls_views.first_page, name='first_page'),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
	path('new/', views.PollCreateView.as_view(), name='poll-create'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published', default=timezone.now)
	asked_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

	def __str__(self):
		return self.question_text

	def get_absolute_url(self):
		return reverse('polls:index')


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	choice_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

	def __str__(self):
		return self.choice_text

class Phone(models.Model):
	name = models.CharField(max_length= 9000)
	price = models.IntegerField(default=0)
	brand = models.CharField(max_length=200)
	rating = models.IntegerField(default=0)
	specification = models.TextField()

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Question

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class AskQuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields= ['question_text', 'pub_date', 'asked_by']

polls/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Phone
from .serializers import api_exampleSerializer

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.views.generic import CreateView

from django.contrib import messages
from .forms import UserRegisterForm, AskQuestionForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime

class PollCreateView(LoginRequiredMixin, CreateView):
	model = Question
	fields = ['question_text']

	def form_valid(self, form):
		form.instance.asked_by = self.request.user
		return super().form_valid(form)

class IndexView(LoginRequiredMixin, generic.ListView):
	login_url = '/login/'
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:20]


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    login_url = '/login/'

class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    login_url = '/login/'


@login_required
def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {'question': question,'error_message': "You didn't select a choice."})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def first_page(request):
	return render(request, 'polls/first_page.html')


class exampleList(APIView):
	def get(self, request):
		values = Phone.objects.all()
		serializer = api_exampleSerializer(values, many = True)
		return Response(serializer.data)

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Your account has been created! You are now able to login')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, 'polls/register.html', {'form': form})

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
	<title></title>
</head>
<body>
	<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
		<div class="container">
		<a class="navbar-brand mr-4" href="">Your Polls </a>
		<div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">
		<a class="nav-item nav-link" href="">Home</a>
		<a class="nav-item nav-link" href="">About</a>
			</div>
			<div class="navbar-nav">
						{% if user.is_authenticated %}
						    <a class="nav-item nav-link" href="{% url 'polls:poll-create' %}">New Poll</a>
							<a class="nav-item nav-link" href="">Profile</a>
							<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>

						{% else %}
							<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
							<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
						{% endif %}
					</div>
		</div>
	</div>
	</nav>
	</header>
	<main>
		{% block content %}
		{% endblock %}
	</main>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

{% endblock content %}

polls/templates/polls/first_page.html
{% extends "polls/base.html" %}
{% block content %}
<h3>Welcome to the site of Queries and its Answers</h3>

{% endblock content %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
<h3>Welcome {{ user.username }}</h3>

{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a>asked by <a href="">{{ question.asked_by }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

{% endblock content %}

polls/templates/polls/login.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class= "form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				{{ form}}
			</fieldset>
			<div class= "form-group">
				<button class= "btn btn-outline-info" type="submit">Log In</button>
				<small class="text-muted ml-2">
					<a href="">Forgot Password?</a>
					
				</small>
			</div>
			
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
			</small>
		</div>	
		
	</div>
{% endblock content %}

polls/templates/polls/logout.html
{% extends 'polls/base.html' %}
{% block content %}

<h2>You have been logged out</h2>
		<div class="border-top pt-3">
			<small class="text-muted">
				 <a href="{% url 'login' %}">Log In Again</a>
			</small>
		</div>
{% endblock content %}

polls/templates/polls/question_form.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class= "form-group">
			<legend class="border-bottom mb-4">Create Poll</legend>
			{{ form|crispy }}
		</fieldset>
		<div class= "form-group">
			<button class= "btn btn-outline-info" type="submit">Post</button>
		</div>			
	</form>					
</div>
{% endblock content %}

polls/templates/polls/register.html
{% extends 'polls/base.html' %}
{% block content %}

{% load crispy_forms_tags %}
<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class= "form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				{{ form|crispy }}
			</fieldset>
			<div class= "form-group">
				<button class= "btn btn-outline-info" type="submit">Sign Up</button>
			</div>
			
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
			</small>
		</div>	
		
	</div>

{% endblock content %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}